### ISSUE TITLE
Missing data error

### ISSUE THREAD

**Issue by PaimonWheeWhee** [CTK-WARRIOR/Anime-Hub#3]
Pretty sure this has something to do with the anime scraper. But I don't know how to fix this, and it's even happening when I fork the main branch without making any edits on it.
It pops this error in the console
```js
(node:452) UnhandledPromiseRejectionWarning: ReferenceError: Cannot access 'data' before initialization
    at /home/runner/Anime-Hub/index.js:23:10
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/runner/Anime-Hub/index.js:22:14
(node:452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:452) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:452) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at /home/runner/Anime-Hub/index.js:67:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Comment by CTK-WARRIOR** [comment]
its unable to fetch the website which is why this error is coming, i forget to handle this error.

**Comment by PaimonWheeWhee** [comment]
Is there a way to fix that though? It was working fine the day before yesterday but then yesterday it was kinda not working :(

**Comment by CTK-WARRIOR** [comment]
i will see

**Comment by jeydinpham** [comment]
You still seeing about it .-.
Happened again and I'm sad

**Comment by CTK-WARRIOR** [comment]
Ah Sorry, let me check

**Comment by CTK-WARRIOR** [comment]
This issue is already been resolved :D, the problem was that from the website i was fetching was down which is why we got that error but the site is now up.
